class DanmakuData {
  /// [optional] unique id of danmaku and corresponding create/update time,
  /// They are usually generated by database
  int? id;
  int? createdAt;
  int? updatedAt;

  /// [optional] Used to identify which user send this danmaku
  String? userToken;

  /// [optional] Used to identify which video this danmaku was send
  int? videoId;

  /// content of the danmaku
  late String content;

  /// [optional] color of the danmaku
  /// Syntax: 0xFFFFFFF
  String? color;

  /// the display position on the screen.
  /// position == 1, top; position == 2, bottom
  late int position;

  /// Time in milliseconds that the danmaku was sent in the video
  late int time;

  DanmakuData({
    this.id,
    this.createdAt,
    this.updatedAt,
    this.userToken,
    this.videoId,
    required this.content,
    this.color,
    required this.time,
    required this.position,
  });

  DanmakuData.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    userToken = json['user_token'];
    videoId = json['post_id'];
    content = json['content'];
    color = json['color'];
    time = json['time'];
    position = json['position'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['user_token'] = userToken;
    data['post_id'] = videoId;
    data['content'] = content;
    data['color'] = color;
    data['time'] = time;
    data['position'] = position;
    return data;
  }
}
